version: '3.7'
services:
  status_bot:
    container_name: riddle-bot
    image: defelo/riddle-bot:latest
    restart: always
    tty: true
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      TOKEN: '[TOKEN]'
